error: an entrypoint that calls `App::run()` does not return `AppExit`
  --> tests/ui/main_return_without_appexit/main.rs:26:16
   |
24 | fn main() {
   |          - help: try: `-> AppExit`
25 |     let mut app = App::new();
26 |     App::new().run();
   |                ^^^^^
   |
   = note: `App::run()` returns `AppExit`, which can be used to determine whether the app exited successfully or not
note: the lint level is defined here
  --> tests/ui/main_return_without_appexit/main.rs:7:9
   |
7  | #![deny(bevy::main_return_without_appexit)]
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: an entrypoint that calls `App::run()` does not return `AppExit`
  --> tests/ui/main_return_without_appexit/main.rs:29:5
   |
24 | fn main() {
   |          - help: try: `-> AppExit`
...
29 |     App::run(&mut app);
   |     ^^^^^^^^^^^^^^^^^^
   |
   = note: `App::run()` returns `AppExit`, which can be used to determine whether the app exited successfully or not

error: an entrypoint that calls `App::run()` does not return `AppExit`
  --> tests/ui/main_return_without_appexit/main.rs:16:20
   |
16 |         App::new().run();
   |                    ^^^^^
...
24 | fn main() {
   |          - help: try: `-> AppExit`
...
37 |     local_macro!();
   |     -------------- in this macro invocation
   |
   = note: `App::run()` returns `AppExit`, which can be used to determine whether the app exited successfully or not
   = note: this error originates in the macro `local_macro` (in Nightly builds, run with -Z macro-backtrace for more info)

error: an entrypoint that calls `App::run()` does not return `AppExit`
  --> tests/ui/main_return_without_appexit/main.rs:19:9
   |
19 |         App::run(&mut app);
   |         ^^^^^^^^^^^^^^^^^^
...
24 | fn main() {
   |          - help: try: `-> AppExit`
...
37 |     local_macro!();
   |     -------------- in this macro invocation
   |
   = note: `App::run()` returns `AppExit`, which can be used to determine whether the app exited successfully or not
   = note: this error originates in the macro `local_macro` (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 4 previous errors

