error: an entrypoint that calls `App::run()` does not return `AppExit`
  --> tests/ui/main_return_without_appexit/muted_expr.rs:17:16
   |
13 | fn main() {
   |          - help: try: `-> AppExit`
...
17 |     App::new().run();
   |                ^^^^^
   |
   = note: `App::run()` returns `AppExit`, which can be used to determine whether the app exited successfully or not
note: the lint level is defined here
  --> tests/ui/main_return_without_appexit/muted_expr.rs:9:9
   |
9  | #![deny(bevy::main_return_without_appexit)]
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 1 previous error

